export type LocalGalleryItem = {
  id: string;
  title: string;
  caption: string;
  category: "events" | "projects" | "team" | "other";
  type: "image" | "video";
  src: string;
  order: number;
};

export const localGalleryItems: LocalGalleryItem[] = [
  {
    id: "press-briefing",
    title: "Press briefing",
    caption: "TARV leadership addressing media during an official briefing.",
    category: "events",
    type: "image",
    src: "/gallery/press-briefing.png",
    order: 1,
  },
  {
    id: "press-statement",
    title: "Media statement",
    caption: "A public statement captured during a TVC News interview.",
    category: "events",
    type: "image",
    src: "/gallery/press-statement.png",
    order: 2,
  },
  {
    id: "official-meeting-delegation",
    title: "Official meeting",
    caption: "Delegation meeting in a formal government reception setting.",
    category: "events",
    type: "image",
    src: "/gallery/official-meeting-delegation.png",
    order: 3,
  },
  {
    id: "official-group-portrait",
    title: "Partnership gathering",
    caption: "TARV partners and stakeholders after an official engagement.",
    category: "events",
    type: "image",
    src: "/gallery/official-group-portrait.png",
    order: 4,
  },
  {
    id: "office-visit-delegation",
    title: "Office visit",
    caption: "Visiting delegation during a hosted institutional tour.",
    category: "events",
    type: "image",
    src: "/gallery/office-visit-delegation.png",
    order: 5,
  },
  {
    id: "site-visit-delegation",
    title: "Site visit",
    caption: "On-site engagement during a project and partnership visit.",
    category: "projects",
    type: "image",
    src: "/gallery/site-visit-delegation.png",
    order: 6,
  },
  {
    id: "airport-arrival",
    title: "Arrival",
    caption: "Team and partners arriving for an engagement abroad.",
    category: "team",
    type: "image",
    src: "/gallery/airport-arrival.png",
    order: 7,
  },
  {
    id: "traditional-celebration",
    title: "Celebration",
    caption: "A joyful moment with partners at a traditional celebration.",
    category: "events",
    type: "image",
    src: "/gallery/traditional-celebration.png",
    order: 8,
  },
  {
    id: "formal-banquet",
    title: "Formal banquet",
    caption: "Leadership seated at a formal reception and partnership dinner.",
    category: "events",
    type: "image",
    src: "/gallery/formal-banquet.png",
    order: 9,
  },
  {
    id: "vinci-hapel-joint-venture",
    title: "VINCI × Hapel joint venture",
    caption:
      "Chairman and directors of VINCI Construction with Hapel leadership at their joint venture ceremony.",
    category: "projects",
    type: "image",
    src: "/gallery/vinci-hapel-joint-venture.png",
    order: 10,
  },
  {
    id: "ufuma-road-flagging",
    title: "Ufuma road project",
    caption:
      "Flagging of the Ufuma road project by His Excellency Mr. Peter Obi, Governor of Anambra State.",
    category: "projects",
    type: "image",
    src: "/gallery/ufuma-road-flagging.png",
    order: 11,
  },
  {
    id: "stefanutti-hapel-jet",
    title: "Stefanutti × Hapel partnership",
    caption:
      "Directors of Stefanutti Stocks and Hapel aboard a private jet after their joint venture ceremony.",
    category: "projects",
    type: "image",
    src: "/gallery/stefanutti-hapel-jet.png",
    order: 12,
  },
  {
    id: "ette-abak-commissioning",
    title: "Ette-Abak commissioning",
    caption:
      "Commissioning of the Ette-Abak project by His Excellency Chief Olusegun Obasanjo, President of the Federal Republic of Nigeria.",
    category: "projects",
    type: "image",
    src: "/gallery/ette-abak-commissioning.png",
    order: 13,
  },
  {
    id: "hapel-awards",
    title: "Awards & recognition",
    caption:
      "Commendations and awards recognizing Hapel’s contribution to infrastructure and indigenous road construction.",
    category: "projects",
    type: "image",
    src: "/gallery/hapel-awards.png",
    order: 14,
  },
  {
    id: "modern-residence",
    title: "Modern residence",
    caption: "Contemporary residential architecture from the Hapel project portfolio.",
    category: "projects",
    type: "image",
    src: "/gallery/modern-residence.png",
    order: 15,
  },
  {
    id: "infrastructure-excavation",
    title: "Site excavation",
    caption: "Heavy equipment preparing groundworks for infrastructure delivery.",
    category: "projects",
    type: "image",
    src: "/gallery/infrastructure-excavation.png",
    order: 16,
  },
  {
    id: "infrastructure-hauler",
    title: "Haulage fleet",
    caption: "Articulated dump trucks supporting large-scale earthmoving operations.",
    category: "projects",
    type: "image",
    src: "/gallery/infrastructure-hauler.png",
    order: 17,
  },
  {
    id: "infrastructure-drilling",
    title: "Drilling operations",
    caption: "Specialized drilling equipment deployed on project sites.",
    category: "projects",
    type: "image",
    src: "/gallery/infrastructure-drilling.png",
    order: 18,
  },
  {
    id: "tarvi-video-1",
    title: "TARV highlight reel",
    caption: "Moments from TARV engagements and partnerships across Africa.",
    category: "other",
    type: "video",
    src: "/video/tarvi_1.mp4",
    order: 19,
  },
  {
    id: "tarvi-video-2",
    title: "TARV in action",
    caption: "A closer look at TARV’s work building investment bridges.",
    category: "other",
    type: "video",
    src: "/video/tarvi_2.mp4",
    order: 20,
  },
  {
    id: "tarvi-video-5",
    title: "Project footage 05",
    caption: "Field operations and partnership activity from the TARV network.",
    category: "projects",
    type: "video",
    src: "/video/tarvi_5.mp4",
    order: 21,
  },
  {
    id: "tarvi-video-6",
    title: "Project footage 06",
    caption: "On-the-ground progress across infrastructure and investment engagements.",
    category: "projects",
    type: "video",
    src: "/video/tarvi_6.mp4",
    order: 22,
  },
  {
    id: "tarvi-video-7",
    title: "Project footage 07",
    caption: "Documenting TARV-linked delivery and site activity.",
    category: "projects",
    type: "video",
    src: "/video/tarvi_7.mp4",
    order: 23,
  },
  {
    id: "tarvi-video-8",
    title: "Project footage 08",
    caption: "Highlights from construction and partnership programmes.",
    category: "projects",
    type: "video",
    src: "/video/tarvi_8.mp4",
    order: 24,
  },
  {
    id: "tarvi-video-9",
    title: "Project footage 09",
    caption: "Additional field coverage from TARV and Hapel engagements.",
    category: "projects",
    type: "video",
    src: "/video/tarvi_9.mp4",
    order: 25,
  },
  {
    id: "tarvi-video-10",
    title: "Project footage 10",
    caption: "Site and stakeholder moments from recent programmes.",
    category: "events",
    type: "video",
    src: "/video/tarvi_10.mp4",
    order: 26,
  },
  {
    id: "tarvi-video-11",
    title: "Project footage 11",
    caption: "Closing highlights from TARV’s documented activities.",
    category: "events",
    type: "video",
    src: "/video/tarvi_11.mp4",
    order: 27,
  },
];
